name: "Link Check"
description: "Check that all new links compared to main respond properly"
inputs:
  rootURL:
    description: "The URL that root-relative links will have prepended to them"
  origin:
    description: "If provided, remove given git origin and replace with the value of this option. Necessary for forked repos."
    required: false
  main:
    description: "When using git diff sourcing, diff against this branch"
    default: "main"
  configFile:
    description: "A JSON file in the repo used to configure the link check"
  diff:
    description: "If true, links will be sourced from Git diff output instead of the filesystem"
  dryRun:
    description: "Skip the check on links that otherwise would have one"
  unusedPatternsOnly:
    description: >-
      If true, turns on dryRun and exits after reporting unused link patterns.
  linkIncludePatternFile:
    description: >-
      A string or JSON array of filenames to use as link inclusion files.
      Read as one micromatch pattern per line.
      If no include patterns are provided, all links are checked.
    required: false
  linkIncludePatterns:
    description: >-
      A string or JSON array of micromatch patterns to whitelist links.
      If no include patterns are provided, all links are attempted.
    required: false
  linkExcludePatternFile:
    description: >-
      A string or JSON array of filenames to use as link exclusion files.
      Read as one micromatch pattern per line.
    required: false
  linkExcludePatterns:
    description: >-
      A string or JSON array of micromatch patterns to blacklist links.
      Takes priority over inclusion patterns.
    required: false

  fileIncludePatternFile:
    description: >-
      A string or JSON array of paths to read as link inclusion files.
      Read as one micromatch pattern per line.
      If no include patterns are provided, all files will be scraped for links.
    required: false
  fileIncludePatterns:
    description: >-
      A string or JSON array of micromatch patterns to whitelist files.
      If no include patterns are provided, all files will be scraped for links.
    required: false
  fileExcludePatternFile:
    description: >-
      A string or JSON array of paths to read as link exclusion files.
      Read as one micromatch pattern per line.
      Takes priority over inclusion patterns.
    required: false
  fileExcludePatterns:
    description: >-
      A string or JSON array of micromatch patterns to blacklist files.
      Takes priority over inclusion patterns.
    required: false
  userAgent:
    description: >-
      When specified, will use this string as the `user-agent` header in link check requests.
      Defaults to `Mozilla/5.0 (compatible; Iterative/link-check; +https://github.com/iterative/link-check)`
  output:
    description: >-
      A string or JSON array of output methods to use. "consoleLog" and
      "checksAction" are available. Can be specified as a string to use one
      strategy, or a JSON array to use multiple.
outputs:
  output:
    description: "A stringified JSON object containing output for LouisBRunner/checks-action"
  conclusion:
    description: "A GitHub Checks-compatible conclusion of the report"
runs:
  using: "node12"
  main: "index.js"
