name: Check new links against deployment
on:
  workflow_call:
    inputs:
      branch:
        type: "string"
        required: false
        description: "The branch to compare against when finding new links to check"
        default: "${{ github.event.repository.default_branch }}"
      failsOnly:
        type: "boolean"
        required: false
        description: "If true, only reports failed links"
        default: true
      outputFile:
        type: "string"
        required: false
        description: "The file the link check report will be written to before publishing"
        default: "link-check-report.md"
      config:
        type: 'string'
        description: 'The path to the link-check config file'
        default: 'config/link-check/config.yml'
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    if:
      github.event.deployment.ref != ${{ inputs.branch }} &&
      github.event.deployment_status.state == 'success'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: iterative/setup-cml@v1
      - run: echo "# Link Check Report" > ${{ inputs.outputFile }}
      - name: Run Link Check
        id: check
        continue-on-error: true
        run: |
          npx repo-link-check \
            ${{ inputs.failsOnly && '-f' || '' }} \
            -d ${{ inputs.branch }} \
            -c ${{ inputs.config }} \
            -r ${{ github.event.deployment.payload.web_url }} \
            >> ${{ inputs.outputFile }}
      - name: Create or update comment
        run: cml comment update --watermark-title="Link Check Report" ${{ inputs.outputFile }}
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
