name: Download Link Check Test

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: scheduled-download-link-check-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  check:
    uses: './.github/workflows/link-check-all.yml'
    with:
      title: 'Whole Site Link Checker Report'
      owner: 'iterative'
      repo: 'link-check'
