name: Check new links against deployment
on:
  workflow_call:
    inputs:
      branch:
        type: "string"
        required: false
        description: "The branch to compare against when finding new links to check"
        default: "${{ github.event.repository.default_branch }}"
      failsOnly:
        type: "boolean"
        required: false
        description: "If true, only reports failed links"
        default: true
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    if:
      github.event.deployment.ref != ${{ inputs.main }} &&
      github.event.deployment_status.state == 'success'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: iterative/setup-cml@v1
      - name: Run Link Check
        id: check
        continue-on-error: true
        run: |
          npx repo-link-check \
            ${{ inputs.failsOnly && '-f' || '' }} \
            -d ${{ inputs.branch }} \
            -c config/link-check/config.yml \
            -r ${{ github.event.deployment.payload.web_url }} \
            > output.md

      - name: Create or update comment
        run: cml send-comment --update output.md
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
